anchor_version = "0.14.0"

#[features]
#seeds = false
#[programs.localnet]
#test_dupacct = "72M3rRCsq5VRCbYH2SftGoNhbjPWN3MGWUWjD6NqFPej"
#toy_token = "Fm9s8U8rq5XZZHukSNM4GaeBacktbXsoYCq41jUswrVW"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run jest --testTimeout 1000000 --verbose"
